---
- hosts: webservers
  become: yes
  gather_facts: yes
  vars:
    root_path: /var/www/html
    index_format: index.php
    http_port: "80"

  tasks:
    - name: installing nginx, php, php-fpm
      apt:
        name: ['nginx', 'php', 'php-fpm']
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"
      
    - name: Removing apache2 packages
      apt:
        name: apache2
        state: absent
        purge: yes
        update_cache: yes
      when: ansible_os_family == "Debian"


    - name: changing the template
      template:
        src: default.j2
        dest: /etc/nginx/sites-available/default

    - name: To copy index.php
      copy:
        src: "./{{index_format}}"
        dest: "{{root_path}}/{{index_format}}"
        
    - name: To allow HTTP on port 80
      ufw:
        rule: allow
        port: "{{http_port}}"
        proto: tcp


    - name: service of nginx restarts
      service:
        name: nginx
        state: restarted


- hosts: haproxy
  become: yes
  gather_facts: yes
  tasks:
    - name: Installation of HAPROXY
      apt:
        name: haproxy
        update_cache: yes
        state: latest
      when: ansible_os_family == "Debian"

    - name: changing the haproxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: To restart HAPROXY
      service:
        name: haproxy
        state: restarted

    - name: Rudimentary template
      template:
        src:  rudimentary_test.sh.j2
        dest: $HOME/rudimentary_test.sh

    - name: Rudimentary test function
      command:  bash $HOME/rudimentary_test.sh
      register: test
      args:
        warn: no
    - debug:
        msg:  "{{test.stdout}}"
