---
- hosts: webservers
  become: yes
  vars:
    root_path: /var/www/html
    index_format: index.php

  tasks:
    - name: installing nginx, php, php-fpm
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - nginx
        - php
        - php-fpm
      when: ansible_os_family == "Debian"

    - name: changing the template
      template:
        src: default.j2
        dest: /etc/nginx/sites-available/default

    - name: To copy index.php
      copy:
        src: "./{{index_format}}"
        dest: "{{root_path}}/{{index_format}}"


    - name: service of nginx restarts
      service:
        name: nginx
        state: restarted


- hosts: haproxy
  become: yes
  tasks:
    - name: Installation of HAPROXY
      apt:
        name: haproxy
        update_cache: yes
        state: latest

    - name: changing the haproxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
          
    - name: To restart HAPROXY
      service:
        name: haproxy
        state: restarted
